language: go

go:
  - 1.8
  - 1.9
  - tip

before_script:
  - make vet

install:
  - go get -v github.com/jteeuwen/go-bindata/...
  - go get -v github.com/elazarl/go-bindata-assetfs/...
  - go get -v github.com/golang/dep/cmd/dep
  - dep ensure

script:
  - make build
