language: go

go:
  - 1.6
  - 1.7
  - tip

install:
  - go get -v github.com/jteeuwen/go-bindata/...
  - go get -v github.com/elazarl/go-bindata-assetfs/...
  - go get -v github.com/Masterminds/glide
  - cd $GOPATH/src/github.com/Masterminds/glide && git checkout tags/0.10.2 && go install && cd -
  - glide install

script:
  - make build
