
# Gopkg.toml example

[[constraint]]
  name = "github.com/codegangsta/cli"
  version = "^1.20.0"

[[constraint]]
  name = "github.com/elazarl/go-bindata-assetfs"

[[constraint]]
  name = "github.com/mnbbrown/mailchimp"

[[constraint]]
  name = "github.com/nlopes/slack"
