apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: website
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: website
    spec:
      containers:
        - image: tantalic/bellinghamcodes-website:1.6.0
          name: website
          ports:
            - containerPort: 80
              protocol: TCP
          env:
            - name: MEETUP_NAME
              value: bellinghamcodes
            - name: TWITTER_USERNAME
              value: bellinghamcodes
            - name: INSTAGRAM_USERNAME
              value: bellinghamcodes
            - name: FACEBOOK_PAGE
              value: bellinghamcodes
            - name: SLACK_TEAM
              valueFrom:
                secretKeyRef:
                  name: slack
                  key: team
            - name: SLACK_TOKEN
              valueFrom:
                secretKeyRef:
                  name: slack
                  key: token
            - name: MAILCHIMP_TOKEN
              valueFrom:
                secretKeyRef:
                  name: mailchimp
                  key: token
            - name: MAILCHIMP_LIST
              valueFrom:
                secretKeyRef:
                  name: mailchimp
                  key: list
