# The following example shows the secrets that should be defined for a
# kubernetes deployment

apiVersion: v1
kind: Secret
metadata:
  name: slack
type: Opaque
data:
  team: 
  token: 
---
apiVersion: v1
kind: Secret
metadata:
  name: mailchimp
type: Opaque
data:
  token: 
  list: 
---
